In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a)
print(b)

[1 2 3]
[5 6 7]


In [3]:
type(a)

numpy.ndarray

Basic Operations of Array

In [4]:
print(a+b)
print(a-b)
print(a*b)

[ 6  8 10]
[-4 -4 -4]
[ 5 12 21]


In [5]:
#creating a 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#creating a 3D array
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
print(arr.shape)  #shape of the array 

(2, 3)


In [8]:
print(arr.ndim) #dimension of the array

2


In [9]:
print(arr.dtype)

int32


In [10]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [12]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [13]:
np.random.randint(10,30, size=(3,3))

array([[13, 24, 20],
       [16, 15, 11],
       [11, 19, 15]])

In [14]:
x = np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])

y = np.array([[1,8,3],
            [3,7,2],
            [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [15]:
print(x+y)
print(x-y)
print(x*y)

[[ 8 10  6]
 [ 5 12  4]
 [ 5 10  4]]
[[ 6 -6  0]
 [-1 -2  0]
 [ 1  0 -2]]
[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [16]:
print(x@y) #matrix multiplication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [17]:
np.dot(x,y) #matrix multiplication

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [18]:
x.prod() #product of all elements in the array

12600

In [19]:
x.mean() #mean of all elements in the array

3.3333333333333335

In [20]:
round(y.mean())

4

In [21]:
x.mean(axis=0) #mean of each column

array([4., 4., 2.])

In [22]:
y.mean(axis=1) #mean of each row

array([4.        , 4.        , 3.33333333])

In [23]:
print(x.sum())
print(x.var())
print(x.std())

30
3.3333333333333335
1.8257418583505538


In [24]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 50)) #median
print(np.percentile(a, 25)) #1st quartile
print(np.percentile(a, 75)) #3rd quartile


5.0
3.0
7.0


In [25]:
b = np.random.randint(11,100, (4,4))
print(b)

[[86 43 64 42]
 [20 29 86 21]
 [34 17 69 36]
 [47 47 84 52]]


In [26]:
print('2x8')
print(b.reshape(2,8))

2x8
[[86 43 64 42 20 29 86 21]
 [34 17 69 36 47 47 84 52]]


In [27]:
print('8x2')
print(b.reshape(8,2))

8x2
[[86 43]
 [64 42]
 [20 29]
 [86 21]
 [34 17]
 [69 36]
 [47 47]
 [84 52]]


In [28]:
print(b.reshape(4,4))

[[86 43 64 42]
 [20 29 86 21]
 [34 17 69 36]
 [47 47 84 52]]


In [29]:
print(b[0]) #first row
print(b[0,2]) #first row, third column
print(b[-1]) #last row
print(b[1:3]) #second and third row
print(b[3:]) #last row

[86 43 64 42]
64
[47 47 84 52]
[[20 29 86 21]
 [34 17 69 36]]
[[47 47 84 52]]


In [32]:
arr = np.array([1,2,3,4], dtype='S') #b'1' means byte string where b is the prefix and 1 is the value
print(arr)

[b'1' b'2' b'3' b'4']
